---
- hosts: zabbix
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Atualizar pacotes e instalar dependências
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present

    - name: Baixar chave GPG do Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker_gpg_key

    - name: Adicionar chave GPG do Docker
      command: apt-key add /tmp/docker_gpg_key

    - name: Adicionar repositório Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Obter informações do sistema para Docker Compose
      shell: uname -s && uname -m
      register: system_info

    - name: Instalar Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ system_info.stdout_lines[0] | trim }}-{{ system_info.stdout_lines[1] | trim }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Baixar repositório Zabbix
      git:
        repo: https://github.com/carryontech/zabbix-docker-compose.git
        dest: /opt/zabbix-docker-compose