---
- hosts: zabbix
  become: yes  # Sobe como root
  tasks:
    - name: Coletar informações sobre o sistema
      ansible.builtin.setup:

    - name: Atualizar pacotes e instalar dependências
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Baixar chave GPG do Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker_gpg_key

    - name: Adicionar chave GPG do Docker
      command: apt-key add /tmp/docker_gpg_key

    - name: Adicionar repositório Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Instalar Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_facts.system }}-{{ ansible_facts.architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Criar diretório para o Zabbix
      file:
        path: /opt/zabbix
        state: directory
        mode: '0755'

    - name: Criar arquivo docker-compose.yml para Zabbix
      copy:
        dest: /opt/zabbix/docker-compose.yml
        content: |
          version: '3'
          services:
            zabbix-server:
              image: zabbix/zabbix-server-mysql:latest
              environment:
                - DB_SERVER_HOST=mysql
                - MYSQL_USER=zabbix
                - MYSQL_PASSWORD=zabbix_password
                - MYSQL_ROOT_PASSWORD=root_password
              ports:
                - "10051:10051"
            mysql:
              image: mysql:8.0.30
              environment:
                - MYSQL_DATABASE=zabbix
                - MYSQL_USER=zabbix
                - MYSQL_PASSWORD=zabbix_password
                - MYSQL_ROOT_PASSWORD=root_password
            zabbix-web:
              image: zabbix/zabbix-web-nginx-mysql:latest
              environment:
                - DB_SERVER_HOST=mysql
                - MYSQL_USER=zabbix
                - MYSQL_PASSWORD=zabbix_password
                - MYSQL_ROOT_PASSWORD=root_password
              ports:
                - "8080:8080"
                - "443:8443"

    - name: Subir containers do Zabbix com Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/zabbix